#!/bin/bash

# Проверяем, переданы ли параметры
if [[ -z "$1" ]]; then
    echo "Использование: $0 <версия> [-l]"
    exit 1
fi

VERSION=$1

# Строим образ без кэша
docker image build --no-cache -t ghcr.io/misha00025/rpchatbot:$VERSION - < ./Dockerfile

# Проверяем, передан ли параметр -l
if [[ "$2" == "-l" ]]; then
    docker image tag ghcr.io/misha00025/rpchatbot:$VERSION ghcr.io/misha00025/rpchatbot:latest
fi