#!/bin/bash

# Проверяем, переданы ли параметры
if [[ -z "$1" ]]; then
    echo "Использование: $0 <версия>"
    exit 1
fi

VERSION=$1
IMAGE=ghcr.io/misha00025/rpchatbot

# Строим образ без кэша
docker image build --no-cache -t $IMAGE:$VERSION - < ./Dockerfile