from Arkadia import Arkadia


token = "vk1.a.WLLCmf8Gvp6Yql--XKPmQN7FueBQRPzFECykO7JyxQptcpPM1Tj7RfKHdLKr4iLEEIaJ5fqIWdH8Ijpf9kpu3I2iWJMiS1DXEqKI_LvaCeKBSB6FPNjiNVPS8_hVKUChR-7oWgdBX-1qRuFjfrVCaBch8Lbdno_zdV1aqgQEC7FGbmDgJr4225qfrftRBq_c2ogDRYtYiDDoGYWK49YpFA"

application = Arkadia(token=token)
application.start()